DROP TABLE IF EXISTS VORGAENGE;

CREATE TABLE VORGAENGE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farbe VARCHAR(250) DEFAULT 'rot',
    fahrzeugTyp VARCHAR(250) DEFAULT 'pkw',
    vorgangsDatum DATETIME DEFAULT CURRENT_TIMESTAMP
    );
